export const texts = {
  app: {
    createTaskModalEyebrow: 'Magical modal',
    createTaskModalTitle: 'New task',
    createTaskSubmitLabel: 'Add to notebook',
    createTaskTitle: 'Create a new notebook task 🦄',
    editTaskModalEyebrow: 'Magical edit modal',
    editTaskModalTitle: 'Edit task',
    editTaskSubmitLabel: 'Save changes',
    editTaskTitle: 'Edit notebook task ✍️',
    notebookSpreadEyebrow: 'Notebook spread',
    notebookSpreadTitle: (activeSpread: number, totalSpreads: number) =>
      `Page ${activeSpread} of ${totalSpreads}`,
    previousSpreadButton: '← Prev',
    nextSpreadButton: 'Next →',
    emptyPageEmoji: '🦄💤',
    emptyPageTitle: 'Time to sleep',
    emptyPageDescription:
      'No more slots on this page. Close the magical notebook and rest under the stars.',
    emptyPageDecorations: '✨ ⭐ 🌸 ⭐ ✨',
  },
  header: {
    eyebrow: 'Magical daily planner',
    title: 'Task Manager 🦄',
    description: 'Pink calendar magic with 30-minute slots and live statuses!',
    currentTimeLabel: 'Current magic time',
    tasksCountLabel: (tasksCount: number) => `${tasksCount} enchanted tasks`,
    addTaskButton: '+ Add task',
    timeIcon: '⏳',
    sparkles: ['✦', '✧', '♡', '✦'],
  },
  taskForm: {
    editTitle: 'Edit task ✨',
    createTitle: 'Create task 🦄',
    titleLabel: 'Title',
    titlePlaceholder: 'e.g. Feed the unicorn',
    timeSlotLabel: 'Time slot',
    cardColorLabel: 'Card color',
    taskIconLabel: 'Task icon',
    editSubmitLabel: 'Save task',
    createSubmitLabel: 'Add task',
    cancelButton: 'Cancel',
  },
  taskCard: {
    editButton: 'Edit',
    deleteButton: 'Delete',
  },
  timeSlot: {
    label: 'notebook slot',
    emptyLine: '✨ Empty notebook line ✨',
    editSubmitLabel: 'Save in this slot',
    editTitle: 'Edit task in notebook ✍️',
  },
} as const